name: ExploitFixer
description: "Advanced anti-exploit plugin for Spigot/Paper servers."
authors: [2LS, Obydux]
version: '3.0.0'
main: dev._2lstudios.exploitfixer.ExploitFixer
api-version: '1.13'
folia-supported: true
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
