name: Gradle Package

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: chmod +x gradlew && ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: build/libs/**.jar
